### Create release notes (tests auto commit)
POST {{function-url}}/release-notes/milestones/all
x-releasenotesmaker-token: {{githubtoken}}
x-functions-key: {{UpdateReleaseNotesKey}}

{
    "AccountName": "lbugnion",
    "RepoName": "tests-auto-commit",
    "BranchName": "master",
    "CommitMessage": "New release notes for V1",
    "SinglePage": false,
    "Projects": [
        {
            "Project": "Client project",
            "ProjectId": 2,
            "Header": [
                "This is header line 1",
                "And this is line 2",
                "And this [is a link](http://rts.ch)"
            ]
        },
        {
            "Project": "Test project API",
            "ProjectId": 1
        },
        {
            "Project": "Tests Auto Commit",
            "IsMainPage": true,
            "Header": [
                "This is header line 1 for the main page",
                "Here [is a link](http://galasoft.ch)"
            ]
        }
    ]
}

### Create release notes (releasenotesmaker)
POST {{function-url}}/release-notes/milestones/all
x-releasenotesmaker-token: {{githubtoken}}
x-functions-key: {{UpdateReleaseNotesKey}}

{
    "AccountName": "lbugnion",
    "RepoName": "ReleaseNotesMaker",
    "BranchName": "main",
    "CommitMessage": "New release notes",
    "SinglePage": false,
    "Projects": [
        {
            "Project": "Infrastructure",
            "ProjectId": 2
        },
        {
            "Project": "API",
            "ProjectId": 1
        },
        {
            "Project": "ReleaseNotesMaker",
            "IsMainPage": true
        }
    ]
}
