### Create release notes
POST {{function-url}}/release-notes/milestones/V1
x-releasenotesmaker-token: {{githubtoken}}
x-functions-key: {{UpdateReleaseNotesKey}}

{
    "AccountName": "lbugnion",
    "RepoName": "releasenotesmaker",
    "BranchName": "main",
    "CommitMessage": "New release notes for V1",
    "Projects": [
        {
            "Project": "API",
            "ProjectId": 1
        }
    ]
}